In [3]:
pip install krippendorff

  Obtaining dependency information for krippendorff from https://files.pythonhosted.org/packages/a7/09/93af46a171e8245539b82f53d25e4191e12c25b26187f86176d9baa29fce/krippendorff-0.6.1-py3-none-any.whl.metadata
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: C:\Users\casti\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [4]:
import pandas as pd
import numpy as np
from krippendorff import alpha

In [5]:
dataset = pd.read_csv('Datasets/Labeled_Dataset.csv')

In [6]:
# Create a mapping for categorical ratings to numerical values
rating_mapping = {"Negative": 0, "Neutral": 1, "Positive": 2}

for column in ["First", "Second", "Third"]:
    dataset[column] = dataset[column].map(rating_mapping)

data_matrix = dataset[["First", "Second", "Third"]].values

print("Data Matrix:")
print(data_matrix)

Data Matrix:
[[0. 0. 0.]
 [2. 1. 2.]
 [0. 0. 0.]
 ...
 [1. 1. 1.]
 [0. 0. 0.]
 [1. 1. 1.]]


In [7]:
# Calculate Fleiss' Kappa
kappa = alpha(data_matrix)
kappa_percentage = kappa * 100

print(f"Fleiss' Kappa: {kappa_percentage:.2f}%")

Fleiss' Kappa: 0.72%
